/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projekt_substratum_compiler_aapt2_Aapt2 */

#ifndef _Included_projekt_substratum_compiler_aapt2_Aapt2
#define _Included_projekt_substratum_compiler_aapt2_Aapt2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projekt_substratum_compiler_aapt2_Aapt2
 * Method:    JNImain
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt2_Aapt2_JNImain
		(JNIEnv *, jobject, jstring);

/*
 * Class:     projekt_substratum_compiler_aapt2_Aapt2
 * Method:    nativeCompile
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt2_Aapt2_nativeCompile
		(JNIEnv *, jclass, jobject);

/*
 * Class:     projekt_substratum_compiler_aapt2_Aapt2
 * Method:    nativeLink
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt2_Aapt2_nativeLink
		(JNIEnv *, jclass, jobject);

/*
 * Class:     projekt_substratum_compiler_aapt2_Aapt2
 * Method:    nativeOptimize
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt2_Aapt2_nativeOptimize
		(JNIEnv *, jclass, jobject);

/*
 * Class:     projekt_substratum_compiler_aapt2_Aapt2
 * Method:    nativeDiff
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt2_Aapt2_nativeDiff
		(JNIEnv *, jclass, jobject);

/*
 * Class:     projekt_substratum_compiler_aapt2_Aapt2
 * Method:    nativeDump
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt2_Aapt2_nativeDump
		(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
